### ISSUE TITLE
Handle simultaneously editings of a post and its translation

### ISSUE THREAD

**Issue by dnaber-de** [inpsyde/MultilingualPress#137]
The default WordPress UI provides a mechanism that prevents users from editing a post which is currently being edited by another post. The technical background is the heartbeat API.

In order to avoid collisions when two persons edit a post and its translation at the same time we should discuss a possible yet practical UI behaviour at first. 

A simple suggestion on this: 
- »Disable« the translation meta box if the corresponding post is currently being edited (»is locked«). 
- Unlock the translation meta box when the corresponding post gets unlocked. 

Questions:
- What should happen to the corresponding translation when someone starts to edit the »source« post? Should it be locked the whole time?
- Alternatively: could there be a smarter solution, like when someone starts writing in a translation meta box the corresponding post gets locked?

**Comment by lkraav** [comment]
Hey all. We have a client situation where multiple team members are actively editing MLP-linked posts in their own country's site, and are constantly overwriting each other's changes. You can imagine the user frustration this causes.

Is this scenario exactly what this issue is about - cross-site heartbeat implementation via MLP content links? Is there any remedy / hack-workaround available? It looks like this issue has significantly stalled, a serious concern :/

cc @tfrommen

**Comment by Dinamiko** [comment]
We are going to work on this in the new version 3.
