### ISSUE TITLE
Quicklink is not seo-friendly

### ISSUE THREAD

**Issue by egoipse** [inpsyde/MultilingualPress#251]
Hi! Your plugin really rocks. Thanks for developing it.

I would correct one issue: the quicklink to posts' other languages versions is not seo-friendly for two reasons. First, the anchor text sucks. Nobody expects to reach a post searching for "English" or "russian" or "Español".

Secondly, since penguin publisher should be very careful with every link published on a site. A poor link could affect not just the target post rank, but also the entire's site.

Since it is not possible to allow sites users to get the translation without a link, let me suggest two alternatives to solve this issue:

1. Allow publishers to add a "nofollow" rel tag to other languages versions links.
2. Allow publisher to chosse another anchor text. For example:

Read in:
- "%%title in spanish%% (en Español)
- "%%title in french%% (en Francais)

And so on...

Menawhile, I'm testing the Mlp_Quicklink.php file to see if it's possible to implement any of those solutions...

**Comment by tfrommen** [comment]
Hi there,

I just implemented a new filter to render `nofollow` quicklinks. A release will probably follow in they next week or two.

If you want to make use of the filter, you can do it like so:

```php
<?php

add_filter( 'multilingualpress.quicklinks_nofollow', '__return_true' );
```

All quicklinks will then have the `rel="alternate nofollow"` attribute.

On the anchor text, which "sucks", we simply disagree. :)
Both the language switcher widget and language menu items are set to carry the name (and/or flag) of the **language**. That's why we decided to design the quicklinks like they are.

Thanks for the issue, though.

Cheers,
Thorsten
