### ISSUE TITLE
Translate CPT-Connections 

### ISSUE THREAD

**Issue by RikeOne** [inpsyde/MultilingualPress#258]
I want to adopt the connections between the custom post types to the translated site (I use the Posts 2 Posts Plugin). I also like to add custom meta data. I already found the solution of @Biont. 
Does anyone know an simple way to implement this in MLP? IN which parts of the plugin I have to implement the addon?
Thank you in advance!

Does it maybe works like this: ?
Mlp_Translatable_post_Data.php
```
		// Get the post connections
        $post_connection = p2p_get_connections( $post_id, 'type', true);

		/** This filter is documented in inc/advanced-translator/Mlp_Advanced_Translator_Data.php */
		$post_data = apply_filters( 'mlp_pre_save_post', $post_data, $this->save_context );
		if ( ! $post_data || ! is_array( $post_data ) ) {
			return;
		}

		$file     = $path = '';
		$fileinfo = array();

		// Check for thumbnail
		if ( current_theme_supports( 'post-thumbnails' ) ) {
			$thumb_id = get_post_thumbnail_id( $post_id );
			if ( 0 < $thumb_id ) {
				$path     = wp_upload_dir();
				$file     = get_post_meta( $thumb_id, '_wp_attached_file', true );
				$fileinfo = pathinfo( $file );
				include_once( ABSPATH . 'wp-admin/includes/image.php' ); //including the attachment function
			}
		}
		// Create the post array
		$new_post = array(
			'post_title'   => $post_data['post_title'],
			'post_content' => $post_data['post_content'],
			'post_status'  => 'publish',
			'post_author'  => $post_data['post_author'],
			'post_excerpt' => $post_data['post_excerpt'],
			'post_date'    => $post_data['post_date'],
			'post_type'    => $post_data['post_type'],
            'connected_type' => $post_connection ['connected_type'],
            'connected_items' => $post_connection ['connected_items'],
            // Create the connection part of the array
           // 'p2p_id' => $post_connection['post_connection'],

		);
```

**Comment by tfrommen** [comment]
Hi there,

I'm sorry, but I don't understand. What is it that are trying to do/solve?

I don't know how exactly Posts 2 Posts works internally, but I assume it's using post IDs - which means you cannot just copy some post's value over to another site (post), just because the post IDs will be completely different.

Can you please elaborate?

Thanks in advance,
Thorsten

P.S.: whatever it is that are trying to do, you should **not** hack plugins files! Anything you might want to have **should** be possible by using one or more of the provided filters and/or actions. If not, we can talk about adding one, if appropriate.

**Comment by RikeOne** [comment]
Hi Thorsten,
thank you for your response.
I like to elaborate what I like to do. Of course I don't like to hack the plugin files. If it is possible to use the provided filters etc, I would be very happy to do this.
The Posts to Posts Plugin works with Relationship data, stored in two custom database tables:
wp_p2p:
  - p2p_id
  - p2p_from
  - p2p_to
  - p2p_type

wp_p2pmeta:
  - p2p_id
  - meta_id
  - meta_key
  - meta_value
In addition I like to translate custom Metadata like Metadata from the Theme like a Page Header and additional Pictures and additional Text-Metadata. Is this possible? If it is possible, how it works with the MlP-Plugin?
Thanks in advance,
Rike

Hi Thorsten,
ich vermute, dass du auch deutsch sprichst.
Vielen Dank für deine Antwort. Natürlich möchte ich nicht in den Plugin-Files rumhacken und wäre sehr glücklich das zu umgehen. 
Das Posts 2 Posts Plugin arbeitet mit Relationship-Daten, welche in folgendem Schema abgespeichert werden:
wp_p2p:
  - p2p_id
  - p2p_from
  - p2p_to
  - p2p_type

wp_p2pmeta:
  - p2p_id
  - meta_id
  - meta_key
  - meta_value
Des Weiteren würde ich gerne zusätzlich zum Beitragsbild, weitere Bilder, ein Headerbild etc. in die englische Version der Seite übersetzen. Ist das sowie die Übersetzung von Custom Metadata möglich?
Ist es außerdem möglich bestimmte Posttypes nur zu spiegeln bzw. in die englische Version der Webseite zu klonen?
Vielen lieben Dank im voraus,
Rike

**Comment by tfrommen** [comment]
Hi Rike,

well, yes, I do speak German, but since the two of us seem to be fine with English as well, I would like to keep the conversation that way, so more people might benefit from it - even though your actual topic might be pretty special. I hope this is OK for you. :)

Thanks for the DB details.
Since I don't know how _Posts 2 Posts_ works exactly, I can only provide you with a blueprint of how you could try to do this yourself.

It seems there is currently no action that you can leverage, so you have to (mis)use a filter (for now), or rather, two: [`mlp_pre_save_post`](https://github.com/inpsyde/MultilingualPress/blob/d88827053603ab0358f4355b131d16540299729f/src/inc/advanced-translator/Mlp_Advanced_Translator_Data.php#L368) and [`mlp_pre_insert_post`](https://github.com/inpsyde/MultilingualPress/blob/d88827053603ab0358f4355b131d16540299729f/src/inc/advanced-translator/Mlp_Advanced_Translator_Data.php#L387). Both filters provide the _save context_ as second argument for every remote post (i.e., translation) when saving a post.

Inside the callback that you attach to these filters, you would do the following:

* read the P2P relationships of the original post (by using the [`real_post_id` element](https://github.com/inpsyde/MultilingualPress/blob/d88827053603ab0358f4355b131d16540299729f/src/inc/advanced-translator/Mlp_Advanced_Translator_Data.php#L130) of the second filter argument, `save_context`);
* for all related posts, determine the according translation in the remote site (by using the [`mlp_get_linked_elements( $post_id, 'post', $blog_id )`](https://github.com/inpsyde/MultilingualPress/blob/d88827053603ab0358f4355b131d16540299729f/src/inc/functions.php#L75) function, and the [`target_blog_id` element](https://github.com/inpsyde/MultilingualPress/blob/d88827053603ab0358f4355b131d16540299729f/src/inc/advanced-translator/Mlp_Advanced_Translator_Data.php#L163) of the `$save_context` argument);
* **set** the P2P data for the remote post according to the individual post IDs of the translation posts in its site.

Hopefully, P2P has some API for setting the relationships of a post or so...?

You have to think about edge cases, like when you have a relationship between posts A and B in site 1, but one of them doesn't have a translation, for example.

Also, since you will be doing lots of redundant stuff (depending on the number of sites in your network), you might want to _cache_ some stuff - in whatever way you think best.

**Important**: make sure that the callback (which you can use for both filters, so you don't have to duplicate anything) returns the unmodified first argument! :)

----

Re: custom metadata...
So far, there is no built-in way to _translate_ custom metadata, sorry. This is for a lot of reasons. The most important (and obvious) ones being these:

* we cannot know which of all custom fields should be translatable, and which not;
* we cannot about the _nature_ of each field (what's the allowed data type, are there any conditions to be respected, ...);
* we cannot know about the UI (and cannot rebuild it anyway).

We really hope to be able to do something to this when the Fields API will get merged into Core - and plugins make use of it. To be honest, though. this might take quite a while to get there.

What you can do if you are a developer, however, is make use of plugin actions and insert some UI for the custom fields you are interested in yourself - and also take care of processing these.
Just have a look at the individual [actions fired in the meta box](https://github.com/inpsyde/MultilingualPress/blob/39389981372bfceab56dee6f6f2964572aec9744/src/inc/post-translator/Mlp_Translation_Metabox_View.php#L32) and [in the processing unit](https://github.com/inpsyde/MultilingualPress/blob/39389981372bfceab56dee6f6f2964572aec9744/src/inc/advanced-translator/Mlp_Advanced_Translator_Data.php#L339), respectively.

----

Re: _mirroring_ CPTs...
I take it you just want to _copy_ all relevant data of a post to all translations, no matter what's in the according Translation meta box, is this correct?
If so, you could, again, hook into the two filters from before ([`mlp_pre_save_post`](https://github.com/inpsyde/MultilingualPress/blob/d88827053603ab0358f4355b131d16540299729f/src/inc/advanced-translator/Mlp_Advanced_Translator_Data.php#L368) and [`mlp_pre_insert_post`](https://github.com/inpsyde/MultilingualPress/blob/d88827053603ab0358f4355b131d16540299729f/src/inc/advanced-translator/Mlp_Advanced_Translator_Data.php#L387)), but this time actually use them as filters. :)
Overwrite all relevant data in the first argument (the `$new_post_data` array) with the data from the original post (to be found in the [`source_post` element](https://github.com/inpsyde/MultilingualPress/blob/d88827053603ab0358f4355b131d16540299729f/src/inc/advanced-translator/Mlp_Advanced_Translator_Data.php#L128) in the second argument, `$save_context`).

----

Phew, that was a lot! :)

Hope that helps.
Thorsten

**Comment by RikeOne** [comment]
Hi Torsten,
thank you very much for detailed answer, taking time and the helpful suggestions.
I'll try to implement...
Thanks a lot!
Rike
