### ISSUE TITLE
Categories and tags don't autocomplete when second language added (/bg), giving 404 *read description

### ISSUE THREAD

**Issue by kaziqta** [inpsyde/MultilingualPress#290]
#### Version Information

* PHP: 7.0.1
* WordPress: 4.8.2

#### Steps to Reproduce

Examples with my website

1. When you open: https://www.djentmag.com/our-pick/40-days-later-faceless/ - root language
2. Add /bg - https://www.djentmag.com/bg/our-pick/40-days-later-faceless/ - slug is redirected
3. Category or tag -  https://www.djentmag.com/category/artists/ - root language
4. /bg slug added https://www.djentmag.com/bg/category/artists/ - gives 404

#### What I Expected

To act like 2^

#### What Happened Instead

Well explained in 3 and 4

Awesome plugin! Wouldn't want to create a website with other multilingual option, that is why I wanted to contribute with that example  :)

UPDATE:
Just found it gives 404, when in the slug there is a combination of Cyrillic and English (write to me when you want me to show it, so I can update) - https://www.djentmag.com/bg/изпълнители/банда-sleepers/ (example, I removed it, so users don't get the 404 from that)

**Comment by tfrommen** [comment]
Hi there,

I'm afraid I don't understand.

Are you talking about being _redirected_ (which actually is only _correcting_) to a slug that is pretty _similar_ to the one you just entered? This is Core WordPress functionality, and not specific to MultilingualPress.

For example your _Sleepers_ post from above. The (current) correct URL is https://www.djentmag.com/bg/%d0%b8%d0%b7%d0%bf%d1%8a%d0%bb%d0%bd%d0%b8%d1%82%d0%b5%d0%bb%d0%b8/sleepers/. If I slightly mis-type it, for example, by leaving off the last "s", I still end up on the correct URL, because WordPress guesses what the correct one could be.
Try for yourself: https://www.djentmag.com/bg/%d0%b8%d0%b7%d0%bf%d1%8a%d0%bb%d0%bd%d0%b8%d1%82%d0%b5%d0%bb%d0%b8/sleeper/ (<- is missing the last "s").

So, I don't see how MultilingualPress is involved here, nor what we can do.

Can you elaborate a little, or is it like I described before?

Thanks,
Thorsten

**Comment by kaziqta** [comment]
take note at 3 and 4, the redirect to tags and categories don't work, I think it may be related to the cyrillic in the slug, check that out:
https://www.djentmag.com/bg/category/artists/

**Comment by tfrommen** [comment]
WordPress does not perform this kind of _guessing_ for categories, (only for posts).

This is unrelated to MultilingualPress.

**Comment by kaziqta** [comment]
alright, 10x :)
