### ISSUE TITLE
Polylang to MultilingualPress

### ISSUE THREAD

**Issue by iamkingsleyf** [inpsyde/MultilingualPress#311]
Hello;

I am using Polylang at the moment on single install and would like to switch to Multi sites but i have no idea  how to migrate my published translations.

Regards

**Comment by bueltge** [comment]
Polylang store all posts in each table, default WP and create a relationship between posts with same content, different language via custom taxonomy. 
I think you should export all posts via WP Export default and install all posts in a new Multisite installation. On the export should you create an export for each language, maybe you can split via taxonomy. For MLP is it necessary that you have all posts to each language in one site, one site in the network for one language, region. MLP runs with the default WP tables on posts and meta data, so that you can import with the default importer. Only the relationship is now an manual tasks. However maybe you have not to much posts so that is possible to do that.

**Comment by iamkingsleyf** [comment]
The English site has 3k+ LIVE post only the French and Spanish are less than 50 each....

The option i have here is covert my single wp to wp MU then delete the translated articles and upload them back again

**Comment by Dinamiko** [comment]
@iamkingsleyf There is no currently functionality implemented to import data from Polylang but we can create an extension for the new MultilingualPress version 3 in the future is there is demand for this funcitonality.
