### ISSUE TITLE
Installing the plugin and tables are not created if the DB collation is utf8mb4

### ISSUE THREAD

**Issue by luisarn** [inpsyde/MultilingualPress#319]
#### Version Information
* WordPress: 4.9.8
* MultilingualPress: 2.11.1
* MySQL: 5.6.29

#### Steps to Reproduce
1. Install the plugin
2. Network activate

#### What I Expected
Plugin to install correctly and create the necessary tables.

#### What Happened Instead
Tables are not being created.
Errors in MySQL because the installation script is trying to use the collation utf8_general_ci on an utf8mb4_general_ci database.

**Comment by widoz** [comment]
Hi @luisarn,

I tried to activate the plugin in an installation that use the collation utf8mb4_general_ci and I'm not able to replicate your same issue.

I debugged the installation phase when the tables are created and I get the correct sql query.

Would be nice if you could debug part of the installation by storing some debugging data from `\Mlp_Db_Installer::get_wp_charset_collate` the file is `multilingualpress/src/inc/db/Mlp_Db_Installer.php`.

Alternatively it's possible to see the entire error you get?

Below you'll se my queries.

```
CREATE TABLE wp_mlp_languages (
	ID bigint unsigned NOT NULL auto_increment,
	english_name tinytext,
	native_name tinytext,
	custom_name tinytext NOT NULL DEFAULT '',
	is_rtl tinyint(1) unsigned DEFAULT 0,
	iso_639_1 VARCHAR(20),
	iso_639_2 VARCHAR(20),
	wp_locale tinytext,
	http_name VARCHAR(20),
	priority tinyint(1) unsigned DEFAULT 10,
	PRIMARY KEY  (ID),
	KEY http_name (http_name)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE wp_multilingual_linked (
	ml_id INT NOT NULL AUTO_INCREMENT,
	ml_source_blogid bigint(20) NOT NULL,
	ml_source_elementid bigint(20) NOT NULL,
	ml_blogid bigint(20) NOT NULL,
	ml_elementid bigint(20) NOT NULL,
	ml_type varchar(20) CHARACTER SET utf8 NOT NULL,
	PRIMARY KEY  (ml_id),
	KEY blog_element (ml_blogid,ml_elementid)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE wp_mlp_site_relations (
	ID INT NOT NULL AUTO_INCREMENT,
	site_1 bigint(20) NOT NULL,
	site_2 bigint(20) NOT NULL,
	PRIMARY KEY  (ID),
	UNIQUE KEY site_combinations (site_1,site_2)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

**Comment by luisarn** [comment]
Hi @widoz 

I removed the mlp tables and forced the install_plugin to run again and these are the errors that occurred:

`CREATE TABLE portal_mlp_languages (
ID bigint unsigned NOT NULL auto_increment,
english_name tinytext,
native_name tinytext,
custom_name tinytext NOT NULL DEFAULT '',
is_rtl tinyint(1) unsigned DEFAULT 0,
iso_639_1 VARCHAR(20),
iso_639_2 VARCHAR(20),
wp_locale tinytext,
http_name VARCHAR(20),
priority tinyint(1) unsigned DEFAULT 10,
PRIMARY KEY (ID),
KEY http_name (http_name)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8_general_ci

BLOB/TEXT column 'custom_name' can't have a default value

CREATE TABLE portal_multilingual_linked (
ml_id INT NOT NULL AUTO_INCREMENT,
ml_source_blogid bigint(20) NOT NULL,
ml_source_elementid bigint(20) NOT NULL,
ml_blogid bigint(20) NOT NULL,
ml_elementid bigint(20) NOT NULL,
ml_type varchar(20) CHARACTER SET utf8 NOT NULL,
PRIMARY KEY (ml_id),
KEY blog_element (ml_blogid,ml_elementid)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8_general_ci

COLLATION 'utf8_general_ci' is not valid for CHARACTER SET 'utf8mb4'

CREATE TABLE portal_mlp_site_relations (
ID INT NOT NULL AUTO_INCREMENT,
site_1 bigint(20) NOT NULL,
site_2 bigint(20) NOT NULL,
PRIMARY KEY (ID),
UNIQUE KEY site_combinations (site_1,site_2)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8_general_ci

COLLATION 'utf8_general_ci' is not valid for CHARACTER SET 'utf8mb4'
`

**Comment by widoz** [comment]
@luisarn I see.

I made some research in the code and I see that basically if you have a libmysql version >= 5.5.3 or mysqlnd version >= 5.0.9 and charset is 'utf8mb4' the collation have to be `utf8mb4_unicode_ci` unless it's possible to use `utf8mb4_unicode_520_ci` but that's not the case.

By default the collation is `'utf8_general_ci'`
As you can see at https://github.com/WordPress/WordPress/blob/master/wp-includes/wp-db.php#L726 that it change if some values matches in https://github.com/WordPress/WordPress/blob/master/wp-includes/wp-db.php#L753 

So if you are saying you have the Mysql version 5.6.29, something here `( $this->use_mysqli && ! ( $this->dbh instanceof mysqli ) ) || empty( $this->dbh )` doesn't match.

For additional informations about the collation set see https://github.com/WordPress/WordPress/blob/master/wp-includes/wp-db.php#L3484

As far as I understand your problem is related with WordPress rather than MultilingualPress, so we have to debug some `wpdb` properties values in order to understand why you have this problem.

I tried to set the collation in my db to `utf8mb4_unicode_ci` but when I go to create the table using MLP I always see my collation as `utf8mb4_unicode_ci` and i discovered that.

Could you kindly debug the values for wpdb properties: `use_mysqli`, `dbh` and for the client version?

You can do it in a specific plugin or in theme functions.php file for example by using this snippet.

`
add_action('wp_loaded', function () {

    global $wpdb;

    echo 'WPDB USE MSQLI: ' . $wpdb->use_mysqli . '<br/>';
    echo 'EMPTY DBH: ' . (int)empty($wpdb->dbh) . '<br/>';

    if ($wpdb->use_mysqli) {
        $client_version = mysqli_get_client_info();
    } else {
        $client_version = mysql_get_client_info();
    }

    echo 'DB VERSION: ' . $wpdb->db_version() . '<br/>';
    echo 'WPDB CLIENT VERSION: ' . $client_version . '<br/>';
    echo 'WPDB HAS CAP utf8mb4: ' . (int)$wpdb->has_cap('utf8mb4');
});
`

You output should look like this:

`
WPDB USE MSQLI: 1
EMPTY DBH: 0
DB VERSION: 5.5.55
WPDB CLIENT VERSION: mysqlnd 5.0.11-dev - 20120503 - ... DB ID ...
WPDB HAS CAP utf8mb4: 1
`

**Comment by luisarn** [comment]
Hi @widoz 

I think I figured the origin of the problem.
It's neither WP or Multilingual Press. It's actually a problem within Hyper DB drop in.

**With Hyper DB:**
`WPDB USE MSQLI: 
EMPTY DBH: 0

Fatal error: Uncaught Error: Call to undefined function mysql_get_client_info()`

**Without Hyper DB:**
`WPDB USE MSQLI: 1
EMPTY DBH: 0
DB VERSION: 5.6.29
WPDB CLIENT VERSION: mysqlnd 5.0.12-dev - 20150407 - $Id: b396954eeb2d1d9ed7902b8bae237b287f21ad9e $
WPDB HAS CAP utf8mb4: 1`

The HyperDB doesn't have an official support of utf8mb4 and it overrides the collation with utf8 on SQL preparation, which is the root cause of my issue.

Thanks you @widoz for guiding me to the right direction that the problem might be WP related.

**Comment by luisarn** [comment]
Upgrading the HyperDB to 1.5 seems to solve the Fatal error and the results are:

WPDB USE MSQLI: 1
EMPTY DBH: 0
DB VERSION: 5.6.29
WPDB CLIENT VERSION: mysqlnd 5.0.12-dev - 20150407 - $Id: b396954eeb2d1d9ed7902b8bae237b287f21ad9e $
WPDB HAS CAP utf8mb4: 0

**Comment by widoz** [comment]
@luisarn Glad that you solved the issue and thank you for having share the solution with us.
